import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "glass-border": "rgba(255, 255, 255, 0.1)",
        "surface-container-lowest": "#060e20",
        "surface-container-low": "#131b2e",
        "surface-container": "#171f33",
        "surface-container-high": "#222a3d",
        "surface-container-highest": "#2d3449",
        "surface": "#0b1326",
        "surface-bright": "#31394d",
        "surface-dim": "#0b1326",
        "surface-variant": "#2d3449",
        "on-surface": "#dae2fd",
        "on-surface-variant": "#bbcabf",
        "on-background": "#dae2fd",
        "background": "#0b1326",
        "primary": "#4edea3",
        "primary-container": "#10b981",
        "on-primary": "#003824",
        "on-primary-container": "#00422b",
        "primary-fixed": "#6ffbbe",
        "primary-fixed-dim": "#4edea3",
        "on-primary-fixed": "#002113",
        "on-primary-fixed-variant": "#005236",
        "inverse-primary": "#006c49",
        "secondary": "#ddb7ff",
        "secondary-container": "#6f00be",
        "on-secondary": "#490080",
        "on-secondary-container": "#d6a9ff",
        "secondary-fixed": "#f0dbff",
        "secondary-fixed-dim": "#ddb7ff",
        "on-secondary-fixed": "#2c0051",
        "on-secondary-fixed-variant": "#6900b3",
        "tertiary": "#ffb3af",
        "tertiary-container": "#fc7c78",
        "on-tertiary": "#650911",
        "on-tertiary-container": "#711419",
        "tertiary-fixed": "#ffdad7",
        "tertiary-fixed-dim": "#ffb3af",
        "on-tertiary-fixed": "#410005",
        "on-tertiary-fixed-variant": "#842225",
        "outline": "#86948a",
        "outline-variant": "#3c4a42",
        "error": "#ffb4ab",
        "error-container": "#93000a",
        "on-error": "#690005",
        "on-error-container": "#ffdad6",
        "inverse-surface": "#dae2fd",
        "inverse-on-surface": "#283044",
        "surface-tint": "#4edea3",
        "deep-slate": "#0f172a",
        "emerald-glow": "#10b981",
        "pulse-purple": "#a855f7",
        "heatmap-0": "rgba(30, 41, 59, 0.5)",
        "heatmap-1": "rgba(16, 185, 129, 0.2)",
        "heatmap-2": "rgba(16, 185, 129, 0.5)",
        "heatmap-3": "rgba(16, 185, 129, 0.8)",
        "heatmap-4": "#10b981",
      },
      fontFamily: {
        "jakarta": ["Plus Jakarta Sans", "sans-serif"],
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "2xl": "1rem",
        "3xl": "1.5rem",
        "full": "9999px",
      },
    },
  },
  plugins: [],
};
export default config;
